### ISSUE TITLE
Cannot build in release mode

### ISSUE THREAD

**Issue by peci1** [xbmc/imagedecoder.heif#7]
I tried building in RelWithDebInfo mode, but the build fails when building heic file `box.cc` on unused variable (which is somewhere set to be treated as error). That's because the variable is only checked using assert, which is a no-op in release mode. But that seems to be an upstream error. Can't you somehow pass a flag to upstream to not treat it as error?

**Comment by mkreisl** [comment]
Same here:

```
/usr/src/xbian/xbian-package-xbmc/build/rpi2-matrix/working/cmake/addons/build/libheif/src/libheif/libheif/box.cc:1032:12: error: variable ‘success’ set but not used [-Werror=unused-but-set-variable]
       bool success = istr->seek(extent.offset + item.base_offset);
            ^~~~~~~
/usr/src/xbian/xbian-package-xbmc/build/rpi2-matrix/working/cmake/addons/build/libheif/src/libheif/libheif/box.cc: In member function ‘heif::Error heif::Box_idat::read_data(std::shared_ptr<heif::StreamReader>, uint64_t, uint64_t, std::vector<unsigned char>&) const’:
/usr/src/xbian/xbian-package-xbmc/build/rpi2-matrix/working/cmake/addons/build/libheif/src/libheif/libheif/box.cc:2463:8: error: variable ‘success’ set but not used [-Werror=unused-but-set-variable]
   bool success;
        ^~~~~~~
cc1plus: all warnings being treated as errors
```

Please deactivate option `all warnings being treated as errors`

**Comment by notspiff** [comment]
sadly this is not our doing, but something done by the upstream. we'd have to patch their build system.

**Comment by Rechi** [comment]
If you submit a PR, which patches the build system to not error on unused variables, we'll accept it.

**Comment by mkreisl** [comment]
Where's the maintainer of this addon?

IMO this addon is completely broken. Tried this to build on my 64bit Linux box, got another issue:

If x265 lib is installed (probably incl devel stuff?), libheif will be build with this library, but unfortunately this lib is not loaded which leads in unresolved symbols:

```
May 20 16:30:05 0 16:30:05.128 T:139766233151232   ERROR: Unable to load /usr/local/xbmc/18.0/lib64/kodi/addons/imagedecoder.heif/imagedecoder.heif.so.1.0.1, reason: /usr/local/xbmc/18.0/lib64/kodi/addons/imagedecoder.heif/imagedecoder.heif.so.1.0.1: undefined symbol: x265_version_str
```

After deactivating check for x265 availability here https://github.com/strukturag/libheif/blob/master/libheif/CMakeLists.txt#L31, modules loads but shows black picture already described in issue https://github.com/xbmc/imagedecoder.heif/issues/6

**Comment by notspiff** [comment]
not supposed to link against x265 - so we might have to patch out that test as well. i'm in the process of updating to libheif 1.4.0, i guess i can embed it there. it works fine for my test files on my amd64 box, including the camel sample from your link (using system libheif on ubuntu bionic).

**Comment by mkreisl** [comment]
@notspiff 
Today I was trying your repo and being happy to confirm, that with recent PR addon is building and working now w/o any issues

Check for x265 is still there, but it's not so important, at least for me. I'm patching patch `depends/common/libheif/05-find-libde265-without-pkg.patch` and this is working for me

```
diff --git a/depends/common/libheif/05-find-libde265-without-pkg.patch b/depends/common/libheif/05-find-libde265-without-pkg.patch
index f4ff8dd..b4fa4e4 100644
--- a/depends/common/libheif/05-find-libde265-without-pkg.patch
+++ b/depends/common/libheif/05-find-libde265-without-pkg.patch
@@ -11,10 +11,11 @@ diff --git a/libheif/CMakeLists.txt b/libheif/CMakeLists.txt
 index d730dfd..f302039 100644
 --- a/libheif/CMakeLists.txt
 +++ b/libheif/CMakeLists.txt
-@@ -29,6 +29,10 @@ if(UNIX)
+@@ -28,7 +28,10 @@
+ if(UNIX)
    include (${CMAKE_ROOT}/Modules/FindPkgConfig.cmake)
    pkg_check_modules (LIBDE265 libde265)
-   pkg_check_modules (X265 x265)
+-  pkg_check_modules (X265 x265)
 +else()
 +  find_path(de265_INCLUDE_DIR NAMES libde265/de265.h)
 +  set(LIBDE265_CFLAGS /I${de265_INCLUDE_DIR})
```

Thanks for your excellent work

**Comment by notspiff** [comment]
update has been merged, including the x265 probe removal. thanks for testing.
